# Generated by Django 6.0.7 on 2026-07-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoiceitem_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='nhif_rebate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='NHIF/SHA rebate amount', max_digits=10),
        ),
    ]
