# Generated by Django 6.0.7 on 2026-07-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='TENOCARE HOSPITAL', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('telephone', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
            ],
            options={
                'verbose_name': 'Hospital Setting',
                'verbose_name_plural': 'Hospital Settings',
            },
        ),
    ]
