# Generated by Django 6.0.7 on 2026-07-24 07:06

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hospitalsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_code', models.CharField(default=core.models.generate_item_code, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('MEDICINE', 'Medicines'), ('LAB_TEST', 'Laboratory Tests'), ('RADIOLOGY', 'Radiology Services'), ('ULTRASOUND', 'Ultrasound Services'), ('PROCEDURE', 'Procedures'), ('NURSING', 'Nursing Services'), ('MEDICAL_SUPPLIES', 'Medical Supplies'), ('CONSULTATION', 'Consultation Services'), ('REGISTRATION', 'Registration Services'), ('WARD_CHARGES', 'Ward Charges'), ('OTHER', 'Other Billable Services')], max_length=30)),
                ('description', models.TextField(blank=True, default='')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_of_measure', models.CharField(default='Unit', help_text='e.g., Unit, Tablet, Test, Session, Night', max_length=50)),
                ('department', models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('LABORATORY', 'Laboratory'), ('RADIOLOGY', 'Radiology'), ('CONSULTATION', 'Consultation'), ('NURSING', 'Nursing'), ('ADMISSION', 'Admission'), ('REGISTRATION', 'Registration'), ('ADMINISTRATION', 'Administration'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
