# Generated by Django 6.0.7 on 2026-07-24 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='normal_range',
            field=models.CharField(blank=True, default='', help_text='Reference range for lab tests (e.g., 70-100 mg/dL)', max_length=200),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, default='', help_text='Measurement unit for lab tests (e.g., mg/dL, x10^9/L)', max_length=50),
        ),
    ]
