# Generated by Django 6.0.7 on 2026-07-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_normal_range_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalsetting',
            name='nhif_sha_rebate_per_night',
            field=models.DecimalField(decimal_places=2, default=2240, help_text='NHIF/SHA bed rebate per night for insured inpatients (KSH)', max_digits=10),
        ),
    ]
