# Generated by Django 6.0.7 on 2026-07-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item'),
        ('laboratory', '0002_labrequest_result_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Linked Item Master entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='core.item'),
        ),
    ]
