# Generated by Django 6.0.7 on 2026-07-24 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labtest_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('instructions', models.TextField(blank=True, default='', help_text='Optional instructions for the technician')),
                ('lab_test', models.OneToOneField(help_text='The lab test this template applies to', on_delete=django.db.models.deletion.CASCADE, related_name='template', to='laboratory.labtest')),
            ],
            options={
                'verbose_name': 'Lab Test Template',
                'verbose_name_plural': 'Lab Test Templates',
            },
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Parameter name (e.g., WBC, HB, PLT)', max_length=100)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('normal_range', models.CharField(help_text='e.g., 4.0 - 10.0', max_length=100)),
                ('normal_min', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric lower bound for auto-flagging', max_digits=10, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=2, help_text='Numeric upper bound for auto-flagging', max_digits=10, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='laboratory.labtesttemplate')),
            ],
            options={
                'verbose_name': 'Lab Test Parameter',
                'verbose_name_plural': 'Lab Test Parameters',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LabTestResultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(blank=True, default='', max_length=100)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_values', to='laboratory.labrequest')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='laboratory.labtestparameter')),
            ],
            options={
                'verbose_name': 'Lab Test Result Value',
                'verbose_name_plural': 'Lab Test Result Values',
                'unique_together': {('lab_request', 'parameter')},
            },
        ),
    ]
