# Generated by Django 6.0.7 on 2026-07-23 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admission', '0002_alter_admission_admission_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20)),
                ('primary_diagnosis', models.TextField(blank=True, default='')),
                ('secondary_diagnosis', models.TextField(blank=True, default='')),
                ('reason_for_admission', models.TextField(blank=True, default='')),
                ('history_of_present_illness', models.TextField(blank=True, default='')),
                ('clinical_findings', models.TextField(blank=True, default='')),
                ('investigations_performed', models.TextField(blank=True, default='')),
                ('procedures_done', models.TextField(blank=True, default='')),
                ('treatment_given', models.TextField(blank=True, default='')),
                ('patient_progress', models.TextField(blank=True, default='')),
                ('condition_on_discharge', models.TextField(blank=True, default='')),
                ('doctor_advice', models.TextField(blank=True, default='')),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('lifestyle_advice', models.TextField(blank=True, default='')),
                ('diet_advice', models.TextField(blank=True, default='')),
                ('activity_restrictions', models.TextField(blank=True, default='')),
                ('warning_signs', models.TextField(blank=True, default='')),
                ('doctor_signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='admission.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_summaries_created', to=settings.AUTH_USER_MODEL)),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discharge_summaries_finalized', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discharge Summary',
                'verbose_name_plural': 'Discharge Summaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DischargeMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, default='', max_length=100)),
                ('frequency', models.CharField(blank=True, default='', max_length=100)),
                ('duration', models.CharField(blank=True, default='', max_length=100)),
                ('instructions', models.TextField(blank=True, default='')),
                ('discharge_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_medications', to='discharge.dischargesummary')),
            ],
            options={
                'verbose_name': 'Discharge Medication',
                'verbose_name_plural': 'Discharge Medications',
                'ordering': ['created_at'],
            },
        ),
    ]
