# Generated by Django 6.0.7 on 2026-07-19 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('visit_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('WAITING_TRIAGE', 'Waiting for Triage'), ('IN_TRIAGE', 'In Triage'), ('WAITING_DOCTOR', 'Waiting for Doctor'), ('IN_CONSULTATION', 'In Consultation'), ('WAITING_LAB', 'Waiting for Lab'), ('WAITING_PHARMACY', 'Waiting for Pharmacy'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING_TRIAGE', max_length=30)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Celsius', max_digits=4)),
                ('weight', models.DecimalField(decimal_places=2, help_text='kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='cm', max_digits=5)),
                ('blood_pressure_systolic', models.PositiveIntegerField(help_text='mmHg')),
                ('blood_pressure_diastolic', models.PositiveIntegerField(help_text='mmHg')),
                ('pulse', models.PositiveIntegerField(help_text='bpm')),
                ('respiratory_rate', models.PositiveIntegerField(help_text='breaths/min')),
                ('oxygen_saturation', models.DecimalField(decimal_places=1, help_text='%', max_digits=4)),
                ('chief_complaint', models.TextField()),
                ('nurse_notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_assessments', to='triage.visit')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
    ]
