# Generated by Django 6.0.7 on 2026-07-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0002_alter_visit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('WAITING_TRIAGE', 'Waiting for Triage'), ('IN_TRIAGE', 'In Triage'), ('WAITING_DOCTOR', 'Waiting for Doctor'), ('IN_CONSULTATION', 'In Consultation'), ('WAITING_LAB', 'Waiting for Lab'), ('WAITING_RADIOLOGY', 'Waiting for Radiology'), ('WAITING_PHARMACY', 'Waiting for Pharmacy'), ('ADMISSION_IN_PROGRESS', 'Admission In Progress'), ('DISCHARGED', 'Discharged'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING_TRIAGE', max_length=30),
        ),
    ]
