# Generated by Django 6.0.7 on 2026-07-23 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0003_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('WAITING_TRIAGE', 'Waiting for Triage'), ('IN_TRIAGE', 'In Triage'), ('WAITING_DOCTOR', 'Waiting for Doctor'), ('IN_CONSULTATION', 'In Consultation'), ('WAITING_LAB', 'Waiting for Lab'), ('WAITING_XRAY', 'Waiting for X-Ray'), ('WAITING_ULTRASOUND', 'Waiting for Ultrasound'), ('WAITING_DOCTOR_REVIEW', 'Waiting for Doctor Review'), ('WAITING_PHARMACY', 'Waiting for Pharmacy'), ('ADMISSION_IN_PROGRESS', 'Admission In Progress'), ('DISCHARGED', 'Discharged'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING_TRIAGE', max_length=35),
        ),
        migrations.CreateModel(
            name='VisitEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='triage.visit')),
            ],
            options={
                'verbose_name': 'Visit Event',
                'verbose_name_plural': 'Visit Events',
                'ordering': ['timestamp'],
            },
        ),
    ]
