# Generated by Django 6.0.7 on 2026-07-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_alter_visit_status_visitevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageassessment',
            name='blood_pressure_diastolic',
            field=models.PositiveIntegerField(blank=True, help_text='mmHg', null=True),
        ),
        migrations.AlterField(
            model_name='triageassessment',
            name='blood_pressure_systolic',
            field=models.PositiveIntegerField(blank=True, help_text='mmHg', null=True),
        ),
    ]
