# Generated by Django 6.0.7 on 2026-07-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PHARMACIST', 'Pharmacist'), ('LAB_TECHNICIAN', 'Lab Technician'), ('RADIOLOGIST', 'Radiologist'), ('RECEPTIONIST', 'Receptionist'), ('CASHIER', 'Cashier'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('WARD_MANAGER', 'Ward Manager')], default='RECEPTIONIST', max_length=20),
        ),
    ]
