# Generated by Django 6.0.7 on 2026-07-24 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Linked Item Master entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='core.item'),
        ),
    ]
