# Generated by Django 6.0.7 on 2026-07-19 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '0002_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadiologyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('XRAY', 'X-Ray'), ('ULTRASOUND', 'Ultrasound'), ('MRI', 'MRI'), ('CT_SCAN', 'CT Scan'), ('OTHER', 'Other')], max_length=20)),
                ('body_part', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RadiologyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinical_indication', models.TextField(help_text='Why this imaging is requested')),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent')], default='ROUTINE', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('conclusion', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='radiology/images/')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_requests_created', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_requests', to='triage.visit')),
                ('radiology_service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='radiology.radiologyservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
