# Generated by Django 6.0.7 on 2026-07-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiologyrequest',
            old_name='conclusion',
            new_name='impression',
        ),
        migrations.AddField(
            model_name='radiologyrequest',
            name='result_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FINAL', 'Final')], default='DRAFT', max_length=10),
        ),
        migrations.AlterField(
            model_name='radiologyrequest',
            name='clinical_indication',
            field=models.TextField(blank=True, help_text='Why this imaging is requested'),
        ),
    ]
