# Generated by Django 6.0.7 on 2026-07-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item'),
        ('radiology', '0002_rename_conclusion_radiologyrequest_impression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyservice',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Linked Item Master entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radiology_services', to='core.item'),
        ),
    ]
