# Generated by Django 6.0.7 on 2026-07-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_make_next_of_kin_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('INSURANCE', 'Insurance')], default='INSURANCE', max_length=20),
        ),
    ]
