# Generated by Django 6.0.7 on 2026-07-19 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('triage', '0003_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=50, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='triage.visit')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=100)),
                ('dosage_unit', models.CharField(choices=[('MG', 'mg'), ('ML', 'ml'), ('TABLET', 'tablet(s)'), ('CAPSULE', 'capsule(s)'), ('DROP', 'drop(s)'), ('PUFF', 'puff(s)'), ('UNIT', 'unit(s)')], default='MG', max_length=20)),
                ('frequency', models.CharField(help_text='e.g., 3 times daily', max_length=100)),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Total quantity to dispense', max_digits=10)),
                ('route', models.CharField(blank=True, default='Oral', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='Additional instructions')),
                ('is_dispensed', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultation.consultation')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='inventory.medicine')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
