# Generated by Django 6.0.7 on 2026-07-24 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
        ('core', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Linked Item Master entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='core.item'),
        ),
    ]
